### ISSUE TITLE
Просто тестирую систему отправки ошибок

### ISSUE THREAD

**Issue by tkhirianov** [Fareon/infa_2021_baranov#3]
Вот здесь содержание.
*Звёздочка* и **две звёздочки**

```python
if x > 0:
    print(x)
```

**Comment by tkhirianov** [comment]
Вот так можно ссылаться на коммиты: 3f672b2031d14cd765650db575a95978cf713777

**Comment by tkhirianov** [comment]
Кажется её можно просто закрыть.

**Comment by Fareon** [comment]
Закрываю, проблема не проблема
